[project]
name = "image-blur"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "jinja2>=3.1.5",
    "mangum>=0.19.0",
    "pip>=25.0",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.0",
]
