AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  FastAPI Image Blur App deployed on AWS Lambda

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: API Gateway のステージ名

Globals:
  Function:
    Timeout: 30

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    DependsOn: ApiGatewayRole
    Properties:
      StageName: !Ref StageName
      # API Gateway のアクセスログを CloudWatch Logs に出力する設定
      AccessLogSetting:
        # CloudWatch Logs の LogGroup ARN を指定
        DestinationArn: !GetAtt ApiAccessLogs.Arn
        # 出力するログのフォーマット（必要に応じてカスタマイズ可能）
        Format: "{\"requestId\":\"$context.requestId\",\"ip\":\"$context.identity.sourceIp\",\"caller\":\"$context.identity.caller\",\"user\":\"$context.identity.user\",\"requestTime\":\"$context.requestTime\",\"httpMethod\":\"$context.httpMethod\",\"resourcePath\":\"$context.resourcePath\",\"status\":\"$context.status\",\"protocol\":\"$context.protocol\"}"
      # 各メソッドに対してログやメトリクスの設定を行う
      MethodSettings:
        - ResourcePath: "/*"   # 全リソースに対して
          HttpMethod: "*"      # 全 HTTP メソッドに対して
          LoggingLevel: INFO   # INFO または ERROR（ログの詳細度）
          DataTraceEnabled: true   # リクエスト・レスポンスのデータトレースを有効化
          MetricsEnabled: true     # CloudWatch メトリクスの出力を有効化
      BinaryMediaTypes:
        - 'multipart/form-data'
        - 'image/png'
        - 'image/jpeg'
        - 'image/gif'
        - 'application/octet-stream'

  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayRole.Arn

  # CloudWatch Logs の LogGroup リソース（必要に応じて作成）
  ApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/MyApiLogs
      RetentionInDays: 14  # ログの保持日数（任意）

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.13
      CodeUri: src 
      MemorySize: 512
      Environment:
        Variables:
          STAGE: !Ref StageName
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref MyApi
        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MyApi
